# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDERNUM', models.IntegerField(db_index=True)),
                ('EXCHANGE_CODE', models.CharField(blank=True, max_length=25)),
                ('ORDERTIME', models.DateTimeField()),
                ('PERIOD', models.CharField(max_length=255)),
                ('SECNAME', models.CharField(max_length=255)),
                ('BUYSELL', models.CharField(max_length=5)),
                ('ACCOUNT', models.CharField(max_length=25)),
                ('PRICE', models.FloatField()),
                ('QTY', models.IntegerField()),
                ('VISIBLE_QTY', models.IntegerField(blank=True)),
                ('BALANCE', models.IntegerField()),
                ('VALUE', models.FloatField()),
                ('BROKERREF', models.CharField(blank=True, max_length=225)),
                ('STATUS', models.CharField(max_length=20)),
            ],
        ),
    ]
