# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0002_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ORDERNUM',
        ),
    ]
