# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0004_orders_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='MARGIN',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
