# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0005_orders_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ORDERTIME',
            field=models.CharField(max_length=255),
        ),
    ]
