# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0006_auto_20171008_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ORDERGROUP',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
