# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0007_orders_ordergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TRDACCID', models.CharField(max_length=25, unique=True)),
                ('DAYCREATED', models.DateTimeField()),
                ('FIRMID', models.CharField(max_length=250)),
                ('LIMIT_TYPE', models.CharField(max_length=25)),
                ('LIQUIDITY_COEFF', models.FloatField()),
                ('CBP_PREV_LIMIT', models.FloatField()),
                ('PREV_DATE', models.DateTimeField()),
                ('CBPLIMIT', models.FloatField()),
                ('CBPLUSED', models.FloatField()),
                ('CBPLUSED_FOR_ORDERS', models.FloatField()),
                ('CBPLUSED_FOR_POSITIONS', models.FloatField()),
                ('CBPLPLANNED', models.FloatField()),
                ('VARMARGIN', models.FloatField()),
                ('ACCRUEDINT', models.FloatField()),
                ('OPTIONS_PREMIUM', models.FloatField()),
                ('TS_COMISSION', models.FloatField()),
                ('KGO', models.FloatField()),
                ('CURRCODE', models.CharField(max_length=25)),
                ('REAL_VARMARGIN', models.FloatField()),
            ],
        ),
    ]
