# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0009_tradeaccount_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradeaccount',
            old_name='PREV_DATE',
            new_name='LAST_CLEAR_DATE',
        ),
        migrations.AlterField(
            model_name='tradeaccount',
            name='ACCRUEDINT',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tradeaccount',
            name='CBPLPLANNED',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tradeaccount',
            name='CBPLUSED',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tradeaccount',
            name='CBPLUSED_FOR_ORDERS',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tradeaccount',
            name='CBPLUSED_FOR_POSITIONS',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tradeaccount',
            name='CBP_PREV_LIMIT',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tradeaccount',
            name='CURRCODE',
            field=models.CharField(default='SUR', max_length=25),
        ),
        migrations.AlterField(
            model_name='tradeaccount',
            name='KGO',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='tradeaccount',
            name='LIMIT_TYPE',
            field=models.CharField(default='Cash', max_length=25),
        ),
        migrations.AlterField(
            model_name='tradeaccount',
            name='LIQUIDITY_COEFF',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tradeaccount',
            name='OPTIONS_PREMIUM',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tradeaccount',
            name='REAL_VARMARGIN',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tradeaccount',
            name='TS_COMISSION',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tradeaccount',
            name='VARMARGIN',
            field=models.FloatField(default=0.0),
        ),
    ]
