# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0010_auto_20171009_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRMID', models.CharField(max_length=25)),
                ('TRDACCID', models.CharField(max_length=25)),
                ('SECCODE', models.CharField(max_length=255)),
                ('SEC_SHORT_NAME', models.CharField(max_length=255)),
                ('SEC_EXPIRY_DATE', models.DateTimeField()),
                ('TYPE', models.CharField(max_length=25)),
                ('START_BUY', models.IntegerField(default=0)),
                ('START_SELL', models.IntegerField(default=0)),
                ('START_NET', models.IntegerField(default=0)),
                ('TODAY_BUY', models.IntegerField(default=0)),
                ('TODAY_SELL', models.IntegerField(default=0)),
                ('TOTAL_NET', models.IntegerField(default=0)),
                ('OPEN_BUYS', models.IntegerField(default=0)),
                ('OPEN_SELLS', models.IntegerField(default=0)),
                ('CBPLUSED', models.FloatField(default=0.0)),
                ('CBPLPLANNED', models.FloatField(default=0.0)),
                ('VARMARGIN', models.FloatField(default=0.0)),
                ('AVRPOSNPRICE', models.FloatField()),
                ('POSITIONVALUE', models.FloatField()),
                ('REAL_VARMARGIN', models.FloatField(default=0.0)),
                ('TOTAL_VARMARGIN', models.FloatField(default=0.0)),
            ],
        ),
    ]
