# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0011_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='ORDERGROUP',
            field=models.CharField(default='leg', max_length=255),
        ),
    ]
